home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="index"),
    path('categoria/', views.categoria, name='categoria'),
    path('cadastro-categoria/', views.cadastro_categoria, name='cadastro-categoria'),
    path('editar-categoria/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('detalhes-categoria/<int:id>/', views.detalhes_categoria, name='detalhes_categoria'),
    path('excluir-categoria/<int:id>/', views.excluir_categoria, name='excluir_categoria'),
    
    path('produtos/', views.produtos, name="produtos"),
    path("cadastro-produto/", views.cadastro_produto, name="cadastro-produto"),
    path('detalhes_produto/<int:id>/', views.detalhes_produto, name='detalhes_produto'),
    path('editar_produto/<int:id>/', views.editar_produto, name="editar_produto"),
    path('excluir_produto/<int:id>/', views.excluir_produto , name="excluir_produto"),
    
    path('clientes/', views.clientes, name="clientes"),
    path("cadastro-cliente/", views.cadastro_cliente, name="cadastro-cliente"),
    path('detalhes_cliente/<int:id>/', views.detalhes_cliente, name='detalhes_cliente'),
    path('editar_cliente/<int:id>/', views.editar_cliente, name="editar_cliente"),
    path('excluir_cliente/<int:id>/', views.excluir_cliente , name="excluir_cliente"),
    
    path('ajustar_estoque/<int:id>/', views.ajustar_estoque , name="ajustar_estoque"),
    
    path('teste01/', views.teste_01 , name="teste01"),
    path('teste02/', views.teste_02 , name="teste02"),
    path('teste03/', views.teste_03 , name="teste03"),
    
    path('buscar_dados/<str:app_modelo>/', views.buscar_dados , name="buscar_dados"),
    path('pedido/', views.pedido, name="pedido"),   
    path('pedido/<int:id>/', views.detalhes_pedido, name='detalhes_pedido'),   
    path('novo_pedido/<int:id>/', views.novo_pedido, name='novo_pedido'),
    path('remover_pedido/<int:id>/', views.remover_pedido, name='remover_pedido'),
    path('remover-item-pedido/<int:id>/', views.remover_item_pedido, name="remover_item_pedido"),
    path('editar-item-pedido/<int:id>/', views.editar_item_pedido, name="editar_item_pedido"),
    
    path('registrar_pagamento/<int:id>/', views.registrar_pagamento, name="registrar_pagamento"),
    path('nota-fiscal/<int:id>/', views.gerar_nota_fiscal, name="gerar_nota_fiscal"),
  

]

pweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from decimal import Decimal
import hashlib
import locale
from django.db import models
from django.conf import settings

class Base(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    criado_por = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    
    class Meta:
        abstract = True




class Categoria(Base):
    nome = models.CharField(max_length=100)
    ordem =  models.IntegerField()
    
    def __str__(self):
        return self.nome
    

    
class Produto(Base):
    nome = models.CharField(max_length=250) 
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)    
    img_base64 = models.TextField(blank=True)
    
    @property
    def estoque(self):
        estoque_item, flag_created = Estoque.objects.get_or_create(produto=self, defaults={'qtde': 0})
        return estoque_item
        
    
    def __str__(self):
        return self.nome
        
class Estoque(Base):
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    qtde = models.IntegerField()
    
    def __str__(self):
        return f'{self.produto} - quantidade: {self.qtde}'
    
    
class Cliente(Base):
    nome = models.CharField(max_length=250)
    telefone = models.CharField(max_length=30)
    cpf = models.CharField(max_length=20, unique=True)
    datanasc = models.DateField(verbose_name="Data de nascimento", default="2024/11/03", null=True, blank=True)
    ativo = models.BooleanField(default=True)
    
    def __str__(self):
        return self.nome
    
    @property
    def datanascimento(self):
        if self.datanasc:
            return self.datanasc.strftime("%d/%m/%Y")
        return None
    
class Pedido(Base):
    NOVO = 1
    EM_ANDAMENTO = 2
    CONCLUIDO = 3
    CANCELADO = 4
    STATUS_CHOICES = [
        (NOVO, 'Novo'),
        (EM_ANDAMENTO, 'Em andamento'),
        (CONCLUIDO, 'Concluido'),
        (CANCELADO, 'Cancelado')
    ]
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True)
    produtos = models.ManyToManyField(Produto, through='ItemPedido')
    data_pedido = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    
    
    def __str__(self):
        return f'{self.cliente}'
    
    @property
    def chave_acesso(self):
        """
        Gera uma chave de acesso única baseada no ID do pedido e na data do pedido.
        A chave é um hash SHA256 dos valores concatenados.
        """
        data_str = self.data_pedido.strftime('%Y%m%d%H%M%S')
        raw_string = f"{self.id}{data_str}"
        hash_object = hashlib.sha256(raw_string.encode())
        return hash_object.hexdigest()[:44] 
    
    @property
    def data_pedidof(self): 
        if self.data_pedido:
            return self.data_pedido.strftime('%d/%m/%Y %H:%M')
        return "Data não disponível"

    
    @property
    def total(self):
        """Calcula o total de todos os itens no pedido, formatado como moeda local"""
        total = sum(item.qtde * item.preco for item in self.itempedido_set.all())
        return total
    
    @property
    def qtdeItens(self):
        """Conta a qtde de itens no pedido, """
        return self.itempedido_set.count()
    
    # lista de todos os pagamentos realiados
    @property
    def pagamentos(self):
        return Pagamento.objects.filter(pedido=self)    
    
    #Calcula o total de todos os pagamentos do pedido
    @property
    def total_pago(self):
        """Soma o total pago"""
        total = sum(pagamento.valor for pagamento in self.pagamentos.all())
        return total or 0
    
    
    @property
    def status_display(self):
        """Define o status corretamente baseado no pagamento"""
        if self.total_pago >= self.total and self.total > 0:
            return "Pago"
        return self.get_status_display()

   
    
    @property
    def debito(self):
        return "implementar"
    
    @property
    def produtos_lista(self):
        produtos = self.itempedido_set.all()[:3]
        nomes_produtos = [item.produto.nome for item in produtos]
        return ", ".join(nomes_produtos)
    
    @property
    def icms(self):
        return (self.total * Decimal('0.18')).quantize(Decimal('0.01'))

    @property
    def ipi(self):
        return (self.total * Decimal('0.05')).quantize(Decimal('0.01'))

    @property
    def pis(self):
        return (self.total * Decimal('0.0165')).quantize(Decimal('0.01'))

    @property
    def cofins(self):
        return (self.total * Decimal('0.076')).quantize(Decimal('0.01'))

    @property
    def total_impostos(self):
        return self.icms + self.ipi + self.pis + self.cofins

    @property
    def total_com_impostos(self):
        return self.total + self.total_impostos


    

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.PositiveIntegerField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f'{self.produto.nome } (Qtd: {self.qtde} - Preço Unitário: {self.preco })'
    
    @property
    def subtotal(self):
        return self.qtde * self.preco
    
    def verificar_estoque(self):
        if self.produto.estoque.qtde < self.qtde:
            return False
        
        return True
    
    def atualizar_estoque(self):
        """Decrementa a quantidade do estoque ao salvar um novo item do pedido."""
        estoque = Estoque.objects.filter(produto=self.produto).first()
        if estoque and self.verificar_estoque():
            estoque.qtde -= self.qtde
            estoque.save()  # Importante! Salva a alteração no banco de dados
            return True
        return False
    
class Pagamento(models.Model):
    DINHEIRO = 1
    CARTAO = 2
    PIX = 3
    OUTRA = 4
    FORMA_CHOICES = [
        (DINHEIRO, 'Dinheiro'),
        (CARTAO, 'Cartão'),
        (PIX, 'Pix'),
        (OUTRA, 'Outra'),
    ]


    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    forma = models.IntegerField(choices=FORMA_CHOICES)
    valor = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    data_pgto = models.DateTimeField(auto_now_add=True)
    
    @property
    def data_pgtof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pgto:
            return self.data_pgto.strftime('%d/%m/%Y %H:%M')
        return None

    
    
    
    
    


    
    
    

home/forms.py
from datetime import date
from . models import Categoria, Cliente, Estoque, ItemPedido, Produto, Pedido, Pagamento
from django import forms

class CategoriaForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        max_length=250,
        widget=forms.TextInput(attrs={"class": "form-control",
                                      "id": "id_nome" ,
                                      })
    )
    ordem = forms.DecimalField(
        label="Ordem",
        max_digits=10,
        widget=forms.TextInput(attrs={'class': 'form-control', 'id':'id_ordem'})
    )    
    class Meta:
        model = Categoria
        
        fields = '__all__'
        
        exclude = ['criado_por']
        
class ProdutoForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        max_length=250,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})
    )
   
    
    preco = forms.DecimalField(
        label="Preco",
        decimal_places=2,
        max_digits=10,
        widget=forms.TextInput(attrs={
            'class': 'money form-control',
            'maxlength': 500,
            'placeholder': '0,000,00'})
        
    )
   
    
    img_base64 = forms.HiddenInput()
        
    
    class Meta:
        model = Produto
        fields = '__all__'
        exclude = ['criado_por']
        widgets = {
            'categoria': forms.HiddenInput()
        }
        
    def __init__(self, *args, **kwargs):
        super(ProdutoForm, self).__init__(*args, **kwargs)
        self.fields['preco'].localize = True
        self.fields['preco'].widget.is_localized = True
        
class ClienteForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        widget=forms.TextInput(attrs={'class': 'form-control'})
        
    )
    
    cpf = forms.CharField(
        label="CPF",
        widget=forms.TextInput(attrs={'class': 'cpf form-control'})
    )
    
    telefone = forms.CharField(
        label="Telefone",
        widget=forms.TextInput(attrs={'class':'telefone form-control'})
    )
    
    datanasc = forms.DateField(
        label="Data Nascimento",
        widget=forms.DateInput(attrs={'class': ' data form-control', }, format="%d/%m%Y")
    )
    
    def clean_datanasc(self):
        datanasc = self.cleaned_data.get('datanasc')
        if datanasc and datanasc > date.today():
            raise forms.ValidationError("A data de nascimento não pode estar no futuro.")
        return datanasc
    
    class Meta:
        model = Cliente
        
        fields = '__all__'
        exclude = ['criado_por']
               
class EstoqueForm(forms.ModelForm):
    class Meta:
        model = Estoque
        fields = ['produto', 'qtde']
        
        widgets = {
            'produto': forms.HiddenInput(),
            'qtde': forms.TextInput(attrs={'class': 'inteiro form-control',}),
        }
        
class PedidoForm(forms.ModelForm):    
    class Meta:
        model = Pedido
        fields = ['cliente']
        widgets = {
            'cliente': forms.HiddenInput()
        }
            
class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = ['pedido','produto', 'qtde']
        
        def clean(self):
            cleaned_data = super().clean()
            produto = cleaned_data.get('produto')
            qtde = cleaned_data.get('qtde')
            
            
            if produto and qtde:
                if produto.estoque.qtde < qtde:
                    raise forms.ValidationError(f'Estoque insuficiente! Apenas { produto.estoque.qtde} disponivel')
            
            return cleaned_data


        widgets = {
            'pedido': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'produto': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'qtde':forms.TextInput(attrs={'class': 'form-control',}),
        }


from django import forms
from .models import Pagamento

class PagamentoForm(forms.ModelForm):
    class Meta:
        model = Pagamento
        fields = ['pedido', 'forma', 'valor']
        widgets = {
            'pedido': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'forma': forms.Select(attrs={'class': 'form-control'}),  # Select para escolha da forma de pagamento
            'valor': forms.TextInput(attrs={
                'class': 'money form-control',
                'maxlength': 500,
                'placeholder': '0.000,00'
            }),
        }

    def __init__(self, *args, **kwargs):
        # Pegando o pedido do contexto
        self.pedido = kwargs.pop('pedido', None)
        super(PagamentoForm, self).__init__(*args, **kwargs)
        self.fields['valor'].localize = True
        self.fields['valor'].widget.is_localized = True    

    def clean_valor(self):
        """
        Valida se o valor inserido não excede o valor restante do pedido.
        """
        valor = self.cleaned_data.get('valor')

        if self.pedido:
            total_devido = self.pedido.total - self.pedido.total_pago
            if valor > total_devido:
                raise forms.ValidationError(
                    f"O valor do pagamento ({valor}) excede o total devido ({total_devido})."
                )
        
        if valor <= 0:
            raise forms.ValidationError("O valor do pagamento deve ser maior que zero.")

        return valor

    

home/templates/pedido/detalhes.html
{% extends "base.html" %}


{% block titulo_conteudo %} Detalhes do Pedido #{{ pedido.id }} {% endblock titulo_conteudo %}


{% block conteudo %} 


<p><strong>Cliente:</strong> {{ pedido.cliente.nome }}</p>
<p><strong>Data do Pedido:</strong> {{ pedido.data_pedidof }}</p>
<p><strong>Status:</strong> {{ pedido.get_status_display }}</p>


<hr>
<!-- Formulário para adicionar novos produtos -->
<h5>Adicionar Produto</h5>
<form method="POST">
    {% csrf_token %}
    <p>
     <label for="id_produto_nome">Produto:</label>    
    <input type="text" class="form-control autocomplete" 
            id="id_produto_nome" 
            data-url="{% url 'buscar_dados' 'home.Produto' %}" 
            value="{{item_pedido.produto.nome}}" 
            data-hidden="#id_produto" >
    </p>
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Salvar Produto</button>
    <button type="button" onclick="location.href='{% url 'registrar_pagamento' pedido.id %}'" class="btn btn-primary btn-sm">
      Registrar Pagamento
  </button>
</form>
<hr>
<!-- Tabela de Itens já adicionados ao pedido -->
<h5>Itens do Pedido</h5>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Preço Unitário (R$)</th>
            <th>Total (R$)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for item in pedido.itempedido_set.all %}
        <tr>
            <td>{{ item.produto.nome }}</td>
            <td>{{ item.qtde }}</td>
            <td>{{ item.preco }}</td>
            <td>{{ item.subtotal }}</td>
            <button onClick="location='{% url 'detalhes_pedido' pedido.id %}'" type="button" class="btn btn-primary btn-sm">Detalhes</button>
            <td>
              <a href="{% url 'editar_item_pedido' item.id %}" class="btn btn-warning btn-sm">Editar</a>

            
            <a href="{% url 'remover_item_pedido' item.id %}" class="btn btn-danger btn-sm" 
              onclick="return confirm('Tem certeza que deseja remover este item?');">Remover</a>
             
            </td>         
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock conteudo %}


{% block javascript %}
<script>
    $('#confirm-btn').confirmation({
      rootSelector: '#confirm-btn',
      title: 'Você tem certeza?',
      btnOkLabel: 'Sim',
      btnCancelLabel: 'Não',
      onConfirm: function() {
        alert('Confirmado!');
      },
      onCancel: function() {
        alert('Cancelado!');
      }
    });
  </script>


{% endblock javascript %}

home/templates/pedido/form.html
{% extends "base.html" %}


{% block titulo_conteudo %} Novo Pedido {% endblock titulo_conteudo %}


{% block conteudo %} 




<form method="post">
    {% csrf_token %}    


    <p>
      <label for="id_cliene">Cliente:</label>
      <span class="form-control" >{{form.instance.cliente.nome}}</span>
  
    </p>
    <p>
      <label for="id_data">Data:</label>
      <span class="form-control" >{{ data_atual|date:"d/m/Y H:i" }}</span>
     </p>
  
    <p>
      <label for="id_status">Status:</label>
      <span class="form-control" >{{form.instance.get_status_display}}</span>
     </p>    


    {{ form.as_p }}
    
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
</form>




{% endblock conteudo %}


{% block javascript %}


{% endblock javascript %}

home/templates/pedido/lista.html
{% extends "base.html" %}

{% block titulo_conteudo %} Listagem de Pedidos {% endblock titulo_conteudo %}

{% block conteudo %} 

<div class="barrabotoes">  
  <button onClick="location='{% url 'cadastro-cliente' %}'" type="button" class="btn btn-primary btn-sm">Inserir Novo</button> 
</div>

<table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Cliente</th>
        <th>Data</th>
        <th>Situação</th>
        <th>Produtos</th>
        <th>Total (R$)</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for pedido in lista %}
      <tr>
        <td>{{ pedido.id }}</td>
        <td>{{ pedido.cliente.nome }}</td>
        <td>{{ pedido.data_pedidof }}</td>
        <td>
          {% if pedido.status == pedido.CONCLUIDO %}
              <span class="badge bg-success">Concluído</span>
          {% elif pedido.status == pedido.CANCELADO %}
              <span class="badge bg-danger">Cancelado</span>
          {% elif pedido.status == pedido.EM_ANDAMENTO %}
              <span class="badge bg-warning text-dark">Em Andamento</span>
          {% else %}
              <span class="badge bg-secondary">Novo</span>
          {% endif %}
        </td>
        <td>{{ pedido.produtos_lista }}</td>  
        <td>{{ pedido.total }}</td>      
        <td>          
          <button onClick="location='{% url 'detalhes_pedido' pedido.id %}'" type="button" class="btn btn-primary btn-sm">Detalhes</button>
          {% if pedido.total_pago < pedido.total and pedido.status != pedido.CONCLUIDO %}
        <a href="{% url 'remover_pedido' pedido.id %}" class="btn btn-danger btn-sm" 
           onclick="return confirm('Tem certeza que deseja remover este registro?');">
            <i class="fa fa-trash"></i> Remover
        </a>
    {% endif %}

    <!-- Botão para imprimir nota fiscal (só aparece se o pedido estiver pago) -->
    {% if pedido.total_pago >= pedido.total %}
        <a href="{% url 'gerar_nota_fiscal' pedido.id %}" class="btn btn-info btn-sm" target="_blank">
            <i class="fa fa-print"></i> Nota Fiscal
        </a>
    {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock conteudo %}

home/templates/pedido/pagamento.html
{% extends "base.html" %}


{% block titulo_conteudo %} Registro de Pagamento {% endblock titulo_conteudo %}


{% block conteudo %} 


<p>
    <label for="id_cliene">Pedido:</label>
    <span class="form-control" >{{form.instance.pedido}}</span>
    
  </p>
  <p>
    <label for="id_data">Data:</label>
    <span class="form-control" >{{form.instance.pedido.data_pedidof}}</span>
   </p>




<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
    <button type="button" onclick="location.href='{% url 'detalhes_pedido' pedido.id %}'" class="btn btn-secondary btn-sm">Voltar</button>
</form>






<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Valor (R$)</th>
      <th>Forma</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for pagamento in pagamentos %}
    <tr>
      <td>{{ pagamento.id }}</td>
      <td>{{ pagamento.valor }}</td>
      <td>{{ pagamento.get_forma_display }}</td>
      <td>{{ pagamento.data_pgtof }}</td>


      <td>
        <a href="" class="btn btn-warning btn-sm">Editar</a>
        <a href="" class="btn btn-danger btn-sm" 
        onclick="return confirm('Tem certeza que deseja remover este registro?');">Excluir</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


<hr>
{% endblock conteudo %}


{% block javascript %}
{% endblock javascript %}