home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name="index"),
    path('categoria/', views.categoria, name='categoria'),
    path('cadastro-categoria/', views.cadastro_categoria, name='cadastro-categoria'),
    path('editar-categoria/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('detalhes-categoria/<int:id>/', views.detalhes_categoria, name='detalhes_categoria'),
    path('excluir-categoria/<int:id>/', views.excluir_categoria, name='excluir_categoria'),
    
    path('produtos/', views.produtos, name="produtos"),
    path("cadastro-produto/", views.cadastro_produto, name="cadastro-produto"),
    path('detalhes_produto/<int:id>/', views.detalhes_produto, name='detalhes_produto'),
    path('editar_produto/<int:id>/', views.editar_produto, name="editar_produto"),
    path('excluir_produto/<int:id>/', views.excluir_produto , name="excluir_produto"),
    
    path('clientes/', views.clientes, name="clientes"),
    path("cadastro-cliente/", views.cadastro_cliente, name="cadastro-cliente"),
    path('detalhes_cliente/<int:id>/', views.detalhes_cliente, name='detalhes_cliente'),
    path('editar_cliente/<int:id>/', views.editar_cliente, name="editar_cliente"),
    path('excluir_cliente/<int:id>/', views.excluir_cliente , name="excluir_cliente"),
    
    path('ajustar_estoque/<int:id>/', views.ajustar_estoque , name="ajustar_estoque"),
    
    path('teste01/', views.teste_01 , name="teste01"),
    path('teste02/', views.teste_02 , name="teste02"),
    path('teste03/', views.teste_03 , name="teste03"),
    
    path('buscar_dados/<str:app_modelo>/', views.buscar_dados , name="buscar_dados"),
    path('pedido/', views.pedido, name="pedido"),   
    path('pedido/<int:id>/', views.detalhes_pedido, name='detalhes_pedido'),   
    path('novo_pedido/<int:id>/', views.novo_pedido, name='novo_pedido'),
    path('remover_pedido/<int:id>/', views.remover_pedido, name='remover_pedido'),
    path('remover-item-pedido/<int:id>/', views.remover_item_pedido, name="remover_item_pedido"),
    path('editar-item-pedido/<int:id>/', views.editar_item_pedido, name="editar_item_pedido"),
    
    path('registrar_pagamento/<int:id>/', views.registrar_pagamento, name="registrar_pagamento"),
    path('nota-fiscal/<int:id>/', views.gerar_nota_fiscal, name="gerar_nota_fiscal"),
  

]

pweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from decimal import Decimal
import hashlib
import locale
from django.db import models
from django.conf import settings

class Base(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    criado_por = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    
    class Meta:
        abstract = True




class Categoria(Base):
    nome = models.CharField(max_length=100)
    ordem =  models.IntegerField()
    
    def __str__(self):
        return self.nome
    

    
class Produto(Base):
    nome = models.CharField(max_length=250) 
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)
    preco = models.DecimalField(max_digits=10, decimal_places=2)    
    img_base64 = models.TextField(blank=True)
    
    @property
    def estoque(self):
        estoque_item, flag_created = Estoque.objects.get_or_create(produto=self, defaults={'qtde': 0})
        return estoque_item
        
    
    def __str__(self):
        return self.nome
        
class Estoque(Base):
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    qtde = models.IntegerField()
    
    def __str__(self):
        return f'{self.produto} - quantidade: {self.qtde}'
    
    
class Cliente(Base):
    nome = models.CharField(max_length=250)
    telefone = models.CharField(max_length=30)
    cpf = models.CharField(max_length=20, unique=True)
    datanasc = models.DateField(verbose_name="Data de nascimento", default="2024/11/03", null=True, blank=True)
    ativo = models.BooleanField(default=True)
    
    def __str__(self):
        return self.nome
    
    @property
    def datanascimento(self):
        if self.datanasc:
            return self.datanasc.strftime("%d/%m/%Y")
        return None
    
class Pedido(Base):
    NOVO = 1
    EM_ANDAMENTO = 2
    CONCLUIDO = 3
    CANCELADO = 4
    STATUS_CHOICES = [
        (NOVO, 'Novo'),
        (EM_ANDAMENTO, 'Em andamento'),
        (CONCLUIDO, 'Concluido'),
        (CANCELADO, 'Cancelado')
    ]
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True)
    produtos = models.ManyToManyField(Produto, through='ItemPedido')
    data_pedido = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    
    
    def __str__(self):
        return f'{self.cliente}'
    
    @property
    def chave_acesso(self):
        """
        Gera uma chave de acesso única baseada no ID do pedido e na data do pedido.
        A chave é um hash SHA256 dos valores concatenados.
        """
        data_str = self.data_pedido.strftime('%Y%m%d%H%M%S')
        raw_string = f"{self.id}{data_str}"
        hash_object = hashlib.sha256(raw_string.encode())
        return hash_object.hexdigest()[:44] 
    
    @property
    def data_pedidof(self): 
        if self.data_pedido:
            return self.data_pedido.strftime('%d/%m/%Y %H:%M')
        return "Data não disponível"

    
    @property
    def total(self):
        """Calcula o total de todos os itens no pedido, formatado como moeda local"""
        total = sum(item.qtde * item.preco for item in self.itempedido_set.all())
        return total
    
    @property
    def qtdeItens(self):
        """Conta a qtde de itens no pedido, """
        return self.itempedido_set.count()
    
    # lista de todos os pagamentos realiados
    @property
    def pagamentos(self):
        return Pagamento.objects.filter(pedido=self)    
    
    #Calcula o total de todos os pagamentos do pedido
    @property
    def total_pago(self):
        """Soma o total pago"""
        total = sum(pagamento.valor for pagamento in self.pagamentos.all())
        return total or 0
    
    
    @property
    def status_display(self):
        """Define o status corretamente baseado no pagamento"""
        if self.total_pago >= self.total and self.total > 0:
            return "Pago"
        return self.get_status_display()

   
    
    @property
    def debito(self):
        return "implementar"
    
    @property
    def produtos_lista(self):
        produtos = self.itempedido_set.all()[:3]
        nomes_produtos = [item.produto.nome for item in produtos]
        return ", ".join(nomes_produtos)
    
    @property
    def icms(self):
        return (self.total * Decimal('0.18')).quantize(Decimal('0.01'))

    @property
    def ipi(self):
        return (self.total * Decimal('0.05')).quantize(Decimal('0.01'))

    @property
    def pis(self):
        return (self.total * Decimal('0.0165')).quantize(Decimal('0.01'))

    @property
    def cofins(self):
        return (self.total * Decimal('0.076')).quantize(Decimal('0.01'))

    @property
    def total_impostos(self):
        return self.icms + self.ipi + self.pis + self.cofins

    @property
    def total_com_impostos(self):
        return self.total + self.total_impostos


    

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtde = models.PositiveIntegerField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f'{self.produto.nome } (Qtd: {self.qtde} - Preço Unitário: {self.preco })'
    
    @property
    def subtotal(self):
        return self.qtde * self.preco
    
    def verificar_estoque(self):
        if self.produto.estoque.qtde < self.qtde:
            return False
        
        return True
    
    def atualizar_estoque(self):
        """Decrementa a quantidade do estoque ao salvar um novo item do pedido."""
        estoque = Estoque.objects.filter(produto=self.produto).first()
        if estoque and self.verificar_estoque():
            estoque.qtde -= self.qtde
            estoque.save()  # Importante! Salva a alteração no banco de dados
            return True
        return False
    
class Pagamento(models.Model):
    DINHEIRO = 1
    CARTAO = 2
    PIX = 3
    OUTRA = 4
    FORMA_CHOICES = [
        (DINHEIRO, 'Dinheiro'),
        (CARTAO, 'Cartão'),
        (PIX, 'Pix'),
        (OUTRA, 'Outra'),
    ]


    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    forma = models.IntegerField(choices=FORMA_CHOICES)
    valor = models.DecimalField(max_digits=10, decimal_places=2,blank=False)
    data_pgto = models.DateTimeField(auto_now_add=True)
    
    @property
    def data_pgtof(self):
        """Retorna a data no formato DD/MM/AAAA HH:MM"""
        if self.data_pgto:
            return self.data_pgto.strftime('%d/%m/%Y %H:%M')
        return None

    
    
    
    
    


    
    
    

home/forms.py
from datetime import date
from . models import Categoria, Cliente, Estoque, ItemPedido, Produto, Pedido, Pagamento
from django import forms

class CategoriaForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        max_length=250,
        widget=forms.TextInput(attrs={"class": "form-control",
                                      "id": "id_nome" ,
                                      })
    )
    ordem = forms.DecimalField(
        label="Ordem",
        max_digits=10,
        widget=forms.TextInput(attrs={'class': 'form-control', 'id':'id_ordem'})
    )    
    class Meta:
        model = Categoria
        
        fields = '__all__'
        
        exclude = ['criado_por']
        
class ProdutoForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        max_length=250,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})
    )
   
    
    preco = forms.DecimalField(
        label="Preco",
        decimal_places=2,
        max_digits=10,
        widget=forms.TextInput(attrs={
            'class': 'money form-control',
            'maxlength': 500,
            'placeholder': '0,000,00'})
        
    )
   
    
    img_base64 = forms.HiddenInput()
        
    
    class Meta:
        model = Produto
        fields = '__all__'
        exclude = ['criado_por']
        widgets = {
            'categoria': forms.HiddenInput()
        }
        
    def __init__(self, *args, **kwargs):
        super(ProdutoForm, self).__init__(*args, **kwargs)
        self.fields['preco'].localize = True
        self.fields['preco'].widget.is_localized = True
        
class ClienteForm(forms.ModelForm):
    nome = forms.CharField(
        label="Nome",
        widget=forms.TextInput(attrs={'class': 'form-control'})
        
    )
    
    cpf = forms.CharField(
        label="CPF",
        widget=forms.TextInput(attrs={'class': 'cpf form-control'})
    )
    
    telefone = forms.CharField(
        label="Telefone",
        widget=forms.TextInput(attrs={'class':'telefone form-control'})
    )
    
    datanasc = forms.DateField(
        label="Data Nascimento",
        widget=forms.DateInput(attrs={'class': ' data form-control', }, format="%d/%m%Y")
    )
    
    def clean_datanasc(self):
        datanasc = self.cleaned_data.get('datanasc')
        if datanasc and datanasc > date.today():
            raise forms.ValidationError("A data de nascimento não pode estar no futuro.")
        return datanasc
    
    class Meta:
        model = Cliente
        
        fields = '__all__'
        exclude = ['criado_por']
               
class EstoqueForm(forms.ModelForm):
    class Meta:
        model = Estoque
        fields = ['produto', 'qtde']
        
        widgets = {
            'produto': forms.HiddenInput(),
            'qtde': forms.TextInput(attrs={'class': 'inteiro form-control',}),
        }
        
class PedidoForm(forms.ModelForm):    
    class Meta:
        model = Pedido
        fields = ['cliente']
        widgets = {
            'cliente': forms.HiddenInput()
        }
            
class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = ['pedido','produto', 'qtde']
        
        def clean(self):
            cleaned_data = super().clean()
            produto = cleaned_data.get('produto')
            qtde = cleaned_data.get('qtde')
            
            
            if produto and qtde:
                if produto.estoque.qtde < qtde:
                    raise forms.ValidationError(f'Estoque insuficiente! Apenas { produto.estoque.qtde} disponivel')
            
            return cleaned_data


        widgets = {
            'pedido': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'produto': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'qtde':forms.TextInput(attrs={'class': 'form-control',}),
        }


from django import forms
from .models import Pagamento

class PagamentoForm(forms.ModelForm):
    class Meta:
        model = Pagamento
        fields = ['pedido', 'forma', 'valor']
        widgets = {
            'pedido': forms.HiddenInput(),  # Campo oculto para armazenar o ID
            'forma': forms.Select(attrs={'class': 'form-control'}),  # Select para escolha da forma de pagamento
            'valor': forms.TextInput(attrs={
                'class': 'money form-control',
                'maxlength': 500,
                'placeholder': '0.000,00'
            }),
        }

    def __init__(self, *args, **kwargs):
        # Pegando o pedido do contexto
        self.pedido = kwargs.pop('pedido', None)
        super(PagamentoForm, self).__init__(*args, **kwargs)
        self.fields['valor'].localize = True
        self.fields['valor'].widget.is_localized = True    

    def clean_valor(self):
        """
        Valida se o valor inserido não excede o valor restante do pedido.
        """
        valor = self.cleaned_data.get('valor')

        if self.pedido:
            total_devido = self.pedido.total - self.pedido.total_pago
            if valor > total_devido:
                raise forms.ValidationError(
                    f"O valor do pagamento ({valor}) excede o total devido ({total_devido})."
                )
        
        if valor <= 0:
            raise forms.ValidationError("O valor do pagamento deve ser maior que zero.")

        return valor

    

home/templates/produto/detalhes.html
{% extends 'base.html'%}
{% block title %}Categorias{% endblock %}

{%  block titulo_page %}Detalhes{% endblock %}
{% block conteudo %}

<p>
    <label >ID:</label><br>
    <span class="form-control">{{produto.id}}</span>
   
 </p>
 
 
 <p>
    <label >Nome:</label><br>
    <span class="form-control">{{produto.nome}}</span>
 </p>
 
 
 <p>
    <label >Preoço R$:</label><br>
    <span class="form-control">{{produto.preco}}</span>
 </p>
 
 
 <p>
    <label >Imagen:</label><br>
    <span class="form-control"> 
       <img  src="{{produto.img_base64}} " width="200" height="200">
     </span>
 </p>
 
{% block javascript %}
<script>


    $(document).ready(function() {

        // Configura inicialização das imagens base64 para todo campo da classe img_init
        $('.img_init').each(function() {
            const initialImageBase64 = $(this).val();
            const target_canvas = $(this).data('canvas');
            if (initialImageBase64) {
                loadImage(initialImageBase64,target_canvas);
            }
        });
        
        // Evento acionado quando uma nova imagem é selecionada
        $('.img_upload').on('change', function(event) {
            
            const imagemInput = this.files[0]; // Pega o arquivo selecionado
            var hidden = $(this).data('hidden');  // Pega o campo hidden associado ao file input
            if (imagemInput) {
                const reader = new FileReader();
                reader.readAsDataURL(imagemInput); // Converte a imagem para base64

                reader.onload = function() {
                    const imgBase64 = reader.result; // O resultado da conversão
                    $('#'+hidden).val(imgBase64); // Seta o valor base64 no campo hidden associado ao file input
                    var canvasTarget = $('#'+hidden).data('canvas'); // pega o canvas associado ao compo hidden
                    // Exibe a nova imagem no canvas
                    loadImage(imgBase64,canvasTarget);
                };

                reader.onerror = function(error) {
                    console.log('Erro ao converter a imagem: ', error);
                };
            }
        });
    });
</script>

{% endblock javascript %}
{% endblock %}

home/templates/produto/estoque.html
{% extends "base.html" %}


{% block titulo_conteudo %} Ajuste de Estoque {% endblock titulo_conteudo %}


{% block conteudo %} 
<p>
    <label for="id_produto">Produto:</label>
    <span class="form-control" >{{form.instance.produto.nome}}</span>
    </p>
<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>
</form>
{% endblock conteudo %}


{% block javascript %}{% endblock javascript %}

home/templates/produto/form.html
{% extends "base.html" %}


{% block titulo_conteudo %} Formulário de Produtos {% endblock titulo_conteudo %}


{% block conteudo %} 
<form method="post">
    {% csrf_token %}    
    {{ form.as_p }}


    <p>
        <label for="id_categoria_nome">Categoria:</label>
        <!-- autocomplete -->
        <input type="text" value="{{form.instance.categoria}}" 
            class="form-control autocomplete" 
            id="id_categoria_nome" 
            data-url="{% url 'buscar_dados' 'home.Categoria' %}" 
            data-hidden="#id_categoria" placeholder="Categoria" >
    </p>    


    <fieldset class="fieldset">
        <label for="imagem">Imagem:</label>
        <input type="hidden" 
            id="img_base64"  
            class="img_init" 
            data-canvas="imageCanvas" 
            value="{{form.instance.img_base64}}" 
            name="img_base64">


        <input type="file" id="imagem" 
            name="imagem" 
            data-hidden="img_base64" 
            class="img_upload form-control" 
            accept="image/*"><br>


        <canvas class="canvas"  id="imageCanvas" width="200" height="200"></canvas><br>


    </fieldset>


    <p>
    
</p>


    <button class="btn btn-primary btn-sm" type="submit">Salvar</button>




    


</form>


{% endblock conteudo %}


{% block javascript %}
<script>




    $(document).ready(function() {


        // Configura inicialização das imagens base64 para todo campo da classe img_init
        $('.img_init').each(function() {
            const initialImageBase64 = $(this).val();
            const target_canvas = $(this).data('canvas');
            if (initialImageBase64) {
                loadImage(initialImageBase64,target_canvas);
            }
        });
        
        // Evento acionado quando uma nova imagem é selecionada
        $('.img_upload').on('change', function(event) {
            
            const imagemInput = this.files[0]; // Pega o arquivo selecionado
            var hidden = $(this).data('hidden');  // Pega o campo hidden associado ao file input
            if (imagemInput) {
                const reader = new FileReader();
                reader.readAsDataURL(imagemInput); // Converte a imagem para base64


                reader.onload = function() {
                    const imgBase64 = reader.result; // O resultado da conversão
                   
                    $('#'+hidden).val(imgBase64); // Seta o valor base64 no campo hidden associado ao file input
                    var canvasTarget = $('#'+hidden).data('canvas'); // pega o canvas associado ao compo hidden
                    // Exibe a nova imagem no canvas
                    loadImage(imgBase64,canvasTarget);
                };


                reader.onerror = function(error) {
                    console.log('Erro ao converter a imagem: ', error);
                };
            }
        });
    });
</script>


{% endblock javascript %}

home/templates/produto/lista.html
{% extends 'base.html'%}
{% block title %}Categorias{% endblock %}
{% block cards %}   
    <div class="d-flex justify-content-end  ">
        <a class="btn btn-primary g-2 d=flex align-items-center" href="{% url 'cadastro-produto' %}"><i class="bi bi-plus-circle"></i><span class="ms-2">Produto</span></a>
    </div>     
{% endblock %}

{%  block titulo_page %}Categorias{% endblock %}
{% block conteudo %}
<table class="table table-bordered table-hover mx-auto">
    <thead class="thead-dark">
        <tr>
            <th scope="col">ID</th> 
            <th scope="col">#</th> 
            <th scope="col">Nome</th>
            <th scope="col">Preço</th>
            <th scope="col">Categoria</th>            
            <th scope="col">Qtde</th>              
            <th scope="col">Açoes</th>
        </tr>
    </thead>
    <tbody>
        {% for lista in lista %}
        <tr>
            <td>{{ lista.id }}</td>
            <td>
                <img src="{{ lista.img_base64 }}" width="50" height="50" alt="Imagem do Produto">
            </td>
            
            <td>{{ lista.nome }}</td>
            <td>{{ lista.preco }}</td> 
            <td>{{ lista.categoria }}</td> 
            <td>{{ lista.estoque.qtde }}</td>          
        
            <td style="width: 280px;">
                <!-- <button data-id="{{ lista.id }}" onclick="detalhes(this)" class="btn btn-info">Detalhes</button>
                <button data-id="{{ lista.id }}"  onclick="alterar(this)" class="btn btn-warning">Alterar</button>
                <button data-id="{{ lista.id }}"  onclick="deletar(this)" class="btn btn-danger">Excluir</button> -->

                <a href="{% url 'detalhes_produto' lista.id %}" data-bs-toggle="tooltip" title="Detalhes" class="btn btn-info"><i class="bi bi-eye"></i></a>
                <a href="{% url 'ajustar_estoque' lista.id %}" data-bs-toggle="tooltip" title="Estoque" class="btn btn-warning"><i class="bi bi-box"></i></a>
                <a href="{% url 'editar_produto' lista.id %}" data-bs-toggle="tooltip" title="Editar" class="btn btn-warning"><i class="bi bi-pencil"></i></a>
                <a href="{% url 'excluir_categoria' lista.id %}" data-bs-toggle="tooltip" title="Excluir" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                <!-- <button data-id="{{ lista.id }}"  onclick="location='{% url 'editar_categoria' lista.id %}'" class="btn btn-danger">Excluir</button> -->
            </td>
        </tr>
        {% empty %}
        <td colspan="4" align="center">
            <p>Sem itens</p>
        </td>
        {% endfor %}
        
    </tbody>
</table>

<script>

    function detalhes(button){
        const id = button.getAttribute('data-id');
        
        fetch(`{% url 'detalhes_categoria' 0 %}` .replace('0', id), {
            method: 'GET'
        })
        .then(response => {
            if (!response.ok) {
                throw new Error(`Erro na requisição: ${response.status}`)
            }
        })

    }

    
</script>


{% endblock %}